from src.web.django_views.CobrancaView import CobrancaView
from src.web.django_views.CobrancaDetalhesView import CobrancaDetalhesView
from src.web.django_views.CobrancarPorIdPedidoView import CobrancaPorIdPedidoView
from src.web.django_views.CobrancaWebHookView import CobrancaWebHookView